download_folder: C:\Users\sasik\Downloads
download_filenames:
- 11A BF-02 BUNKER
- BF-02 DPR
download_filenames_map:
  rm: 11A BF-02 BUNKER
  dpr: BF-02 DPR
start_date: 11-Jul-2025
default_timeout: 180
eml:
  url: https://ithelpdesk-ugml.sg4.quickconnect.to/
  file_station: 
    https://ithelpdesk-ugml.sg4.quickconnect.to/?launchApp=SYNO.SDS.App.FileStation3.Instance&SynoToken=laNlkmozfCC0g
  user: voptim
  password: Vop@202425
  hourly_url: 
    https://ithelpdesk-ugml.sg4.quickconnect.to/index.cgi?launchApp=SYNO.SDS.App.FileStation3.Instance&launchParam=openfile%3D%252FV-Optimaise%2520Data%252FBF2%2520AUTO%2520REPORTS%252FCHARGE%2520AND%2520DUMP%252FHOURLY%252F
RM_SHEET_CONFIG:
  COKE:
    sheet_name: LAM COKE
    columns: B:K
    header_row: 3
    col_prefix: COKE_
  NUT COKE:
    sheet_name: NUT COKE
    columns: B:J
    header_row: 2
    col_prefix: NUTCOKE_
  JRS VENTURES:
    sheet_name: 'JRS VENTURES '
    columns: B:S
    header_row: 3
    col_prefix: JRSVENTURES_
  NMDC DONOMALAI:
    sheet_name: NMDC DONOMALAI
    columns: B:R
    header_row: 2
    col_prefix: NMDC_
  LLOYDS CLO:
    sheet_name: LLOYDS CLO
    columns: B:T
    header_row: 2
    col_prefix: LLOYDS_
  GEOMIN CLO:
    sheet_name: GEOMIN CLO
    columns: B:S
    header_row: 2
    col_prefix: GEOMIN_
  SINTER:
    sheet_name: SINTER
    columns: B:Q
    header_row: 2
    col_prefix: SINTER_SP_02_
  QUARTZ:
    sheet_name: QUARTZ
    columns: B:J
    header_row: 2
    col_prefix: QUARTZ_
  DOLOMITE:
    sheet_name: DOLOMITE
    columns: B:L
    header_row: 2
    col_prefix: DOLOMITE_
  PCI:
    sheet_name: PCI ANALYSIS -02
    columns: B:G
    header_row: 6
    col_prefix: PCI_
DPR_CONFIG:
  sheets:
    Jul25:
      sheet_name: Jul'25
      date_row: 5
      date_cols:
      - H
      - AM
      rows:
        Total Coke: 288
        Coke Online - EML: 280
        Total purchase coke: 284
        Prime Nut Coke (B-13): 27
        Yard Nut Coke (B-3): 28
        PCI Coal: 29
        Online+Offline Sinter: 30
        NMDC DONIMALAI: 113
        Geomine industries: 127
        JRS VENTURES: 155
        Lloyds metal energy: 176
        Llyods fines oversize(+10mm): 183
        Dolomite: 250
        Quartzite: 251
      rename_map:
        TOTAL_COKE_MT:
        - Total Coke
        COKE_OFFLINE_MT:
        - Total purchase coke
        PRIME_NUT_COKE_MT:
        - Prime Nut Coke (B-13)
        YARD_NUTCOKE_MT:
        - Yard Nut Coke (B-3)
        PCI_MT:
        - PCI Coal
        SINTER_SP_02_MT:
        - Online+Offline Sinter
        GEOMIN_MT:
        - Geomine industries
        JRSVENTURES_MT:
        - JRS VENTURES
        LLOYDS_MT:
        - Lloyds metal energy
        LLOYDS_FINES_MT:
        - Llyods fines oversize(+10mm)
        DOLOMITE_MT:
        - Dolomite
        QUARTZITE_MT:
        - Quartzite
        NMDC_MT:
        - NMDC DONIMALAI
