download_folder: r"C:\Users\sasik\Downloads"
download_filename: "11A BF-02 BUNKER  2025-26.xlsx"

RM_SHEET_CONFIG:
  COKE:
    sheet_name: "LAM COKE"
    columns: "B:K"
    header_row: 3
    col_prefix: "COKE_"
  NUT COKE:
    sheet_name: "NUT COKE"
    columns: "B:J"
    header_row: 2
    col_prefix: "NUTCOKE_"
  JRS VENTURES:
    sheet_name: "JRS VENTURES "
    columns: "B:S"
    header_row: 3
    col_prefix: "JRSVENTURES_"
  LLOYDS CLO:
    sheet_name: "LLOYDS CLO"
    columns: "B:T"
    header_row: 2
    col_prefix: "LLOYDS_"
  GEOMIN CLO:
    sheet_name: "GEOMIN CLO"
    columns: "B:S"
    header_row: 2
    col_prefix: "GEOMIN_"
  SINTER:
    sheet_name: "SINTER"
    columns: "B:Q"
    header_row: 2
    col_prefix: "SINTER_SP_02_"
  QUARTZ:
    sheet_name: "QUARTZ"
    columns: "B:J"
    header_row: 2
    col_prefix: "QUARTZ_"
  DOLOMITE:
    sheet_name: "DOLOMITE"
    columns: "B:L"
    header_row: 2
    col_prefix: "DOLOMITE_"
